# conda env create --file environment.yml
# mamba env create --file environment.yml
name: rti_synth_pop
channels:
  - conda-forge
dependencies:
  - python=3.11
  - black
  - jupyter
  - jupyterlab
  - matplotlib
  - missingno
  - numpy
  - pandas
  - pandas-flavor
  - pandas-profiling
  - pip
  - pylint
  - pyprojroot
  - python-dotenv
  - seaborn
  - IPython
  - ipykernel
  - IProgress
  - ipywidgets
  - tqdm
  - pyarrow
  - python-duckdb
  - openpyxl
  - pytask
  - xarray
  - rasterio
  - geopandas
  - pointpats
  - joblib=1.4.2
  - pip:
    - censusdata
    - us
    - ipfn
    - -e .
  